version: "3"
services:
  reverseproxy:
      image: ian0549/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: ian0549/udacity-restapi-user
    environment:
      POSTGRESS_USERNAME: ${POSTGRESS_USERNAME}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD} 
      POSTGRESS_DATABASE: ${POSTGRESS_DATABASE} 
      POSTGRESS_HOST: ${POSTGRESS_HOST} 
      AWS_REGION: ${AWS_REGION} 
      AWS_PROFILE: ${AWS_PROFILE} 
      AWS_MEDIA_BUCKET: ${AWS_MEDIA_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: "http://localhost:8100"
  backend-feed:
    image: ian0549/udacity-restapi-feed
    volumes:
      - \Users\IAN CECIL AKOTO\.aws
    environment:
      POSTGRESS_USERNAME: ${POSTGRESS_USERNAME}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD} 
      POSTGRESS_DATABASE: ${POSTGRESS_DATABASE} 
      POSTGRESS_HOST: ${POSTGRESS_HOST} 
      AWS_REGION: ${AWS_REGION} 
      AWS_PROFILE: ${AWS_PROFILE} 
      AWS_MEDIA_BUCKET: ${AWS_MEDIA_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: "http://localhost:8100"
  frontend:
    image: ian0549/udacity-frontend:local
    ports:
      - "8100:80"
